// examples/vue/src/forms/array-field-form.vue
<script setup lang="ts">
import {defineFormComponent, useCreateForm, useFormFieldArray} from '@formulier/vue'
import TextField from '../text-field.vue'

interface FormState {
	galaxies: Galaxy[]
}

interface Galaxy {
	name: string
}

const Form = defineFormComponent<FormState>()
const form = useCreateForm<FormState>({
	initialValues: {
		galaxies: [],
	},
})
const [galaxies, {push, remove, move}] = useFormFieldArray(form, 'galaxies')

function onSubmit(values: FormState) {
	return alert(JSON.stringify(values, null, 2))
}
</script>

<template>
	<div>
		<h1>ArrayFieldForm</h1>

		<Form :form="form" @submit="onSubmit">
			<div className="column">
				<h2>Galaxies</h2>

				<div v-for="(_, index) of galaxies" className="box row" key="{index}">
					<div className="column">
						<button type="button" @click="() => move(index, index - 1)" :disabled="index <= 0">⬆️</button>

						<button type="button" @click="() => move(index, index + 1)" :disabled="index >= galaxies.length - 1">
							⬇️
						</button>

						<button type="button" @click="() => remove(index)">🗑</button>
					</div>

					<div className="column">
						<TextField :name="`galaxies[${index}].name`" label="Galaxy name" />
					</div>
				</div>

				<button type="button" @click="() => push({name: ''})">➕ Add galaxy</button>
			</div>

			<button type="submit">Submit</button>
		</Form>
	</div>
</template>

// examples/react/forms/array-field-form.tsx
import {Form, useCreateForm, useFormFieldArray, useFormInstance} from '@formulier/react'
import * as Field from '../field'

interface Galaxy {
	name: string
}

interface FormState {
	galaxies: Galaxy[]
}

export function ArrayFieldForm() {
	const form = useCreateForm<FormState>({
		initialValues: {
			galaxies: [{name: 'Andromeda Galaxy'}, {name: 'Butterfly Galaxies'}],
		},
	})

	return (
		<div>
			<h1>ArrayFieldForm</h1>

			<Form form={form} onSubmit={values => alert(JSON.stringify(values, null, 2))}>
				<Galaxies />

				<button type="submit">Submit</button>
			</Form>
		</div>
	)
}

function Galaxies() {
	const form = useFormInstance<FormState>()
	const [galaxies, {push, remove, move}] = useFormFieldArray(form, 'galaxies')

	return (
		<div className="column">
			<h2>Galaxies</h2>

			{galaxies.map((_, index) => {
				const handleUp = () => move(index, index - 1)
				const handleDown = () => move(index, index + 1)
				const handleRemove = () => remove(index)

				const canMoveUp = index > 0
				const canMoveDown = index < galaxies.length - 1

				return (
					<div className="box row" key={index}>
						<div className="column">
							<button type="button" onClick={handleUp} disabled={!canMoveUp}>
								⬆️
							</button>

							<button type="button" onClick={handleDown} disabled={!canMoveDown}>
								⬇️
							</button>

							<button type="button" onClick={handleRemove}>
								🗑
							</button>
						</div>

						<div className="column">
							<Field.TextField name={`galaxies[${index}].name`} label="Galaxy name" />
						</div>
					</div>
				)
			})}

			<button type="button" onClick={() => push({name: ''})}>
				➕ Add galaxy
			</button>
		</div>
	)
}
